app_client:
    resource: "@AppBundle/Controller/"
    type:     annotation
   
app_server:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: rest
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
